# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wealthmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanDiegoOpportunity',
            fields=[
                ('opportunity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wealthmap.Opportunity')),
                ('description', models.TextField()),
                ('value_prop', models.CharField(max_length=255)),
                ('application_link', models.TextField()),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
            },
            bases=('wealthmap.opportunity',),
        ),
    ]
