# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_auto_20161028_0314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SanDiegoOpportunity',
            new_name='Opportunity',
        ),
    ]
